// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSfMy9ZmO7yhYY5XK6stUafpQcprFRNb0',
    appId: '1:628399316787:web:ad19bd81eb9e6c434e6846',
    messagingSenderId: '628399316787',
    projectId: 'isattendance-9ef1c',
    authDomain: 'isattendance-9ef1c.firebaseapp.com',
    storageBucket: 'isattendance-9ef1c.firebasestorage.app',
    measurementId: 'G-S3H81KR64B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs_qIGSQrNPgeRYWeUMeMCW6LcWnrPoNU',
    appId: '1:628399316787:android:d98d91f0b47e795b4e6846',
    messagingSenderId: '628399316787',
    projectId: 'isattendance-9ef1c',
    storageBucket: 'isattendance-9ef1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAputk9DnLx_VXz4K3A9DWAWZEegIZW4nA',
    appId: '1:628399316787:ios:8d02930525e56f3e4e6846',
    messagingSenderId: '628399316787',
    projectId: 'isattendance-9ef1c',
    storageBucket: 'isattendance-9ef1c.firebasestorage.app',
    iosBundleId: 'com.example.thesisAttendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAputk9DnLx_VXz4K3A9DWAWZEegIZW4nA',
    appId: '1:628399316787:ios:8d02930525e56f3e4e6846',
    messagingSenderId: '628399316787',
    projectId: 'isattendance-9ef1c',
    storageBucket: 'isattendance-9ef1c.firebasestorage.app',
    iosBundleId: 'com.example.thesisAttendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSfMy9ZmO7yhYY5XK6stUafpQcprFRNb0',
    appId: '1:628399316787:web:8044f5333783c1f04e6846',
    messagingSenderId: '628399316787',
    projectId: 'isattendance-9ef1c',
    authDomain: 'isattendance-9ef1c.firebaseapp.com',
    storageBucket: 'isattendance-9ef1c.firebasestorage.app',
    measurementId: 'G-F58ZYVZ46V',
  );
}
